### ISSUE TITLE
web api reports http code 500 errors

### ISSUE THREAD

**Issue by jhpoelen** [globalbioticinteractions/globalbioticinteractions#1003]
Looking into issue following an web api upgrade causing queries to web api to fail

```
HTTP ERROR 500 javax.servlet.ServletException: org.springframework.web.util.NestedServletException: Handler dispatch failed; nested exception is java.lang.NoSuchMethodError: org.apache.http.client.config.RequestConfig$Builder.setNormalizeUri(Z)Lorg/apache/http/client/config/RequestConfig$Builder;
URI:	/exists
STATUS:	500
MESSAGE:	javax.servlet.ServletException: org.springframework.web.util.NestedServletException: Handler dispatch failed; nested exception is java.lang.NoSuchMethodError: org.apache.http.client.config.RequestConfig$Builder.setNormalizeUri(Z)Lorg/apache/http/client/config/RequestConfig$Builder;
SERVLET:	dispatcher
CAUSED BY:	javax.servlet.ServletException: org.springframework.web.util.NestedServletException: Handler dispatch failed; nested exception is java.lang.NoSuchMethodError: org.apache.http.client.config.RequestConfig$Builder.setNormalizeUri(Z)Lorg/apache/http/client/config/RequestConfig$Builder;
CAUSED BY:	org.springframework.web.util.NestedServletException: Handler dispatch failed; nested exception is java.lang.NoSuchMethodError: org.apache.http.client.config.RequestConfig$Builder.setNormalizeUri(Z)Lorg/apache/http/client/config/RequestConfig$Builder;
CAUSED BY:	java.lang.NoSuchMethodError: org.apache.http.client.config.RequestConfig$Builder.setNormalizeUri(Z)Lorg/apache/http/client/config/RequestConfig$Builder;
Caused by:
javax.servlet.ServletException: org.springframework.web.util.NestedServletException: Handler dispatch failed; nested exception is java.lang.NoSuchMethodError: org.apache.http.client.config.RequestConfig$Builder.setNormalizeUri(Z)Lorg/apache/http/client/config/RequestConfig$Builder;
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:162)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.Server.handle(Server.java:516)
	at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:487)
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:732)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:479)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:277)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
	at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:338)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:315)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:173)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:409)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:883)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1034)
	at java.lang.Thread.run(Thread.java:750)
```

**Comment by jhpoelen** [comment]
Root cause appears to be a httpclient library version conflict.

**Comment by jhpoelen** [comment]
quickfix successfully deployed . . . working on fixing root cause now.

**Comment by jhpoelen** [comment]
Root cause was addressed by preventing an older version of httpclient to propagate in the dependency tree. Quickfix was reverted, and the api appears happy afterwards.

Oef!

**Comment by jhpoelen** [comment]
Issue re-appeared overnight, with a suspicious (empty) search index being published.

first, rolling back the version to the one published in

GloBI Community. (2024). Global Biotic Interactions: Interpreted Data Products hash://md5/946f7666667d60657dc89d9af8ffb909 hash://sha256/4e83d2daee05a4fa91819d58259ee58ffc5a29ec37aa7e84fd5ffbb2f92aa5b8 (0.7) [Data set]. Zenodo. https://doi.org/10.5281/zenodo.11552565

then investigating the root cause of this search index issue.

**Comment by jhpoelen** [comment]
A June 2024 copy of the GloBI search index was installed on the search index server. . . 

```
$ curl --silent -I https://api.globalbioticinteractions.org/exists?accordingTo=globi:globalbioticinteractions/template-dataset | head -2
HTTP/2 200 
date: Sat, 10 Aug 2024 15:39:29 GMT
 ```

investigating root cause now . . .

**Comment by jhpoelen** [comment]
Root cause appears to have been caused by a recent change to help address #999 .

```
ug 10 17:16:46 lepus bash[421657]: [main] INFO org.eol.globi.data.DatasetImporterForRegistry - [jhpoelen/BatFly_Interactions] checking status...
Aug 10 17:16:46 lepus bash[421657]: [main] INFO org.eol.globi.data.DatasetImporterForRegistry - [jhpoelen/BatFly_Interactions] is active, importing...
Aug 10 17:16:47 lepus bash[421657]: java.io.IOError: java.io.IOException: failed to create tmpFile in [/var/cache/globi/index/eol-globi-datasets/target/data]
Aug 10 17:16:47 lepus bash[421657]:         at org.globalbioticinteractions.util.MapDBUtil.newTmpFileDB(MapDBUtil.java:24)
Aug 10 17:16:47 lepus bash[421657]:         at org.globalbioticinteractions.util.MapDBUtil.createBigMap(MapDBUtil.java:15)
Aug 10 17:16:47 lepus bash[421657]:         at org.eol.globi.data.DatasetImporterForMetaTable.indexDependencies(DatasetImporterForMetaTable.java:107)
Aug 10 17:16:47 lepus bash[421657]:         at org.eol.globi.data.DatasetImporterForMetaTable.indexDependencies(DatasetImporterForMetaTable.java:98)
Aug 10 17:16:47 lepus bash[421657]:         at org.eol.globi.data.DatasetImporterForMetaTable.importStudy(DatasetImporterForMetaTable.java:64)
Aug 10 17:16:47 lepus bash[421657]:         at org.eol.globi.data.DatasetImporterForRegistry.importData(DatasetImporterForRegistry.java:89)
Aug 10 17:16:47 lepus bash[421657]:         at org.eol.globi.data.DatasetImporterForRegistry.importData(DatasetImporterForRegistry.java:63)
Aug 10 17:16:47 lepus bash[421657]:         at org.eol.globi.data.DatasetImporterForRegistry.importStudy(DatasetImporterForRegistry.java:43)
Aug 10 17:16:47 lepus bash[421657]:         at org.eol.globi.tool.IndexerDataset.indexDatasets(IndexerDataset.java:79)
Aug 10 17:16:47 lepus bash[421657]:         at org.eol.globi.tool.IndexerDataset.index(IndexerDataset.java:51)
Aug 10 17:16:47 lepus bash[421657]:         at org.eol.globi.tool.CmdCompile.run(CmdCompile.java:32)
Aug 10 17:16:47 lepus bash[421657]:         at picocli.CommandLine.executeUserObject(CommandLine.java:1939)
Aug 10 17:16:47 lepus bash[421657]:         at picocli.CommandLine.access$1300(CommandLine.java:145)
Aug 10 17:16:47 lepus bash[421657]:         at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
Aug 10 17:16:47 lepus bash[421657]:         at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
Aug 10 17:16:47 lepus bash[421657]:         at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
Aug 10 17:16:47 lepus bash[421657]:         at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
Aug 10 17:16:47 lepus bash[421657]:         at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
Aug 10 17:16:47 lepus bash[421657]:         at picocli.CommandLine.execute(CommandLine.java:2078)
Aug 10 17:16:47 lepus bash[421657]:         at org.globalbioticinteractions.elton.Elton4N.run(Elton4N.java:46)
Aug 10 17:16:47 lepus bash[421657]:         at org.globalbioticinteractions.elton.Elton4N.main(Elton4N.java:37)
Aug 10 17:16:47 lepus bash[421657]: Caused by: java.io.IOException: failed to create tmpFile in [/var/cache/globi/index/eol-globi-datasets/target/data]
Aug 10 17:16:47 lepus bash[421657]:         ... 21 more
Aug 10 17:16:47 lepus bash[421657]: Caused by: java.io.IOException: Permission denied
Aug 10 17:16:47 lepus bash[421657]:         at java.io.UnixFileSystem.createFileExclusively(Native Method)
Aug 10 17:16:47 lepus bash[421657]:         at java.io.File.createTempFile(File.java:2063)
Aug 10 17:16:47 lepus bash[421657]:         at org.globalbioticinteractions.util.MapDBUtil.newTmpFileDB(MapDBUtil.java:21)
Aug 10 17:16:47 lepus bash[421657]:         ... 20 more
Aug 10 17:16:47 lepus bash[421657]: [Thread-3] INFO org.eol.globi.db.GraphServiceFactoryImpl - neo4j stopping...
```

This caused the indexing process to be prematurely terminated, and produce an incomplete GloBI search index.

**Comment by jhpoelen** [comment]
Just release a newly rebuilt GloBI search index. 

Apologies for any inconvenience the search index inconsistencies may have caused. Yet another reminder that complex dynamic software infrastructure systems are useful, yet fragile, and need constant maintenance. Dataset archives however, can more easily be archived, distributed etc.  

![image](https://github.com/user-attachments/assets/4434492a-46f6-47ee-81df-77f484a6fd97)
