### ISSUE TITLE
DwC-A reading crashes on malformed data

### ISSUE THREAD

**Issue by jhpoelen** [globalbioticinteractions/globalbioticinteractions#409]
When indexing RSS feed using globi.json:

```json
{ 
  "format": "rss",
  "citation": "MyCoPortal. 2019. http://mycoportal.org/portal/index.php.",
  "resources": {
    "rss": "http://mycoportal.org/portal/webservices/dwc/rss.xml"
  },
  "shouldResolveReferences": false
}
```

```
java.lang.IllegalStateException: java.text.ParseException: Unexpected character ('.' (code 46)): Expected separator ('"' (code 34)) or end-of-line
 at [Source: (BufferedReader); line: 114943, column: 396]
	at org.gbif.dwc.DwcRecordIterator.hasNext(DwcRecordIterator.java:70)
	at org.eol.globi.data.StudyImporterForDwCA.importCore(StudyImporterForDwCA.java:98)
	at org.eol.globi.data.StudyImporterForDwCA.importStudy(StudyImporterForDwCA.java:86)
	at org.eol.globi.data.StudyImporterForRSS.handleDataset(StudyImporterForRSS.java:103)
	at org.eol.globi.data.StudyImporterForRSS.importArchives(StudyImporterForRSS.java:55)
	at org.eol.globi.data.StudyImporterForRSS.importStudy(StudyImporterForRSS.java:48)
	at org.globalbioticinteractions.elton.cmd.CmdUtil.handleSingleNamespace(CmdUtil.java:106)
	at org.globalbioticinteractions.elton.cmd.CmdUtil.lambda$handleNamespaces$1(CmdUtil.java:70)
	at org.globalbioticinteractions.elton.cmd.CmdUtil.handleNamespaces(CmdUtil.java:43)
	at org.globalbioticinteractions.elton.cmd.CmdUtil.handleNamespaces(CmdUtil.java:66)
	at org.globalbioticinteractions.elton.cmd.CmdInteractions.run(CmdInteractions.java:110)
	at org.globalbioticinteractions.elton.cmd.CmdInteractions.run(CmdInteractions.java:98)
	at org.globalbioticinteractions.elton.cmd.CmdLine.run(CmdLine.java:18)
	at org.globalbioticinteractions.elton.cmd.CmdLine.run(CmdLine.java:27)
	at org.globalbioticinteractions.elton.Elton.main(Elton.java:20)
Caused by: java.text.ParseException: Unexpected character ('.' (code 46)): Expected separator ('"' (code 34)) or end-of-line
 at [Source: (BufferedReader); line: 114943, column: 396]
	at org.gbif.utils.file.tabular.JacksonCsvFileReader.read(JacksonCsvFileReader.java:119)
	at org.gbif.utils.file.tabular.JacksonCsvFileReader.read(JacksonCsvFileReader.java:38)
	at org.gbif.dwc.DwcRecordIterator.hasNext(DwcRecordIterator.java:63)
	... 14 more
```

**Comment by jhpoelen** [comment]
Fixed in https://github.com/globalbioticinteractions/globalbioticinteractions/releases/tag/v0.12.10 .
