### ISSUE TITLE
globi index builder fails to stop gracefully - preventing index from updating

### ISSUE THREAD

**Issue by jhpoelen** [globalbioticinteractions/globalbioticinteractions#532]
globi index builder fails to stop gracefully - preventing index from updating

```
 2020-09-11 00:20:48,745 [main] INFO  org.eol.globi.tool.TaxonInteractionIndexer - indexing interactions complete.
 2020-09-11 00:20:48,745 [main] INFO  org.eol.globi.tool.LinkUtil - Linker started...
 2020-09-11 00:26:01,596 [main] INFO  org.eol.globi.tool.LinkUtil - Linker completed in [312]s
 Exception in thread "main" org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.kernel.NeoStoreDataSource@fdf25d9' failed to stop. Please see attached cause exception.
         at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.stop(LifeSupport.java:484)
         at org.neo4j.kernel.lifecycle.LifeSupport.stopInstances(LifeSupport.java:165)
         at org.neo4j.kernel.lifecycle.LifeSupport.stop(LifeSupport.java:147)
         at org.neo4j.kernel.impl.transaction.state.DataSourceManager.stop(DataSourceManager.java:132)
         at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.stop(LifeSupport.java:476)
         at org.neo4j.kernel.lifecycle.LifeSupport.stopInstances(LifeSupport.java:165)
         at org.neo4j.kernel.lifecycle.LifeSupport.stop(LifeSupport.java:147)
         at org.neo4j.kernel.lifecycle.LifeSupport.shutdown(LifeSupport.java:188)
         at org.neo4j.kernel.impl.factory.GraphDatabaseFacade.shutdown(GraphDatabaseFacade.java:285)
         at org.eol.globi.tool.Normalizer.run(Normalizer.java:106)
         at org.eol.globi.tool.Normalizer.main(Normalizer.java:72)
         Suppressed: org.neo4j.kernel.lifecycle.LifecycleException: Failed to transition component 'org.neo4j.kernel.impl.pagecache.PageCacheLifecycle@129704e9' from STOPPED to SHUTTING_DOWN. Please see attached cause exception
                 at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.shutdown(LifeSupport.java:515)
                 at org.neo4j.kernel.lifecycle.LifeSupport.shutdown(LifeSupport.java:203)
                 ... 3 more
         Caused by: java.lang.IllegalStateException: Cannot close the PageCache while files are still mapped:
         neostore.counts.db.a (1 mapping)
         neostore (1 mapping)
         neostore.relationshipgroupstore.db (1 mapping)
         neostore.schemastore.db (1 mapping)
         neostore.labeltokenstore.db (1 mapping)
         neostore.labeltokenstore.db.names (1 mapping)
         neostore.relationshiptypestore.db (1 mapping)
         neostore.relationshiptypestore.db.names (1 mapping)
         neostore.relationshipstore.db (1 mapping)
         neostore.propertystore.db (1 mapping)
         neostore.propertystore.db.arrays (1 mapping)
         neostore.propertystore.db.strings (1 mapping)
         neostore.propertystore.db.index (1 mapping)
         neostore.propertystore.db.index.keys (1 mapping)
         neostore.nodestore.db (1 mapping)
         neostore.nodestore.db.labels (1 mapping)
                 at org.neo4j.io.pagecache.impl.muninn.MuninnPageCache.close(MuninnPageCache.java:521)
                 at org.neo4j.kernel.impl.pagecache.PageCacheLifecycle.shutdown(PageCacheLifecycle.java:42)
                 at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.shutdown(LifeSupport.java:507)
                 ... 4 more
 Caused by: java.lang.NullPointerException
         at org.neo4j.index.impl.lucene.LuceneDataSource.force(LuceneDataSource.java:203)
         at org.neo4j.index.impl.lucene.LuceneIndexImplementation.force(LuceneIndexImplementation.java:181)
         at org.neo4j.kernel.impl.transaction.log.rotation.StoreFlusher.forceEverything(StoreFlusher.java:50)
         at org.neo4j.kernel.NeoStoreDataSource.stop(NeoStoreDataSource.java:1215)
         at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.stop(LifeSupport.java:476)
         ... 10 more
 neo4j stopping...
 neo4j stopped.
 [INFO] ------------------------------------------------------------------------
 [INFO] BUILD FAILURE
 [INFO] ------------------------------------------------------------------------
 [INFO] Total time:  39:32 min
 [INFO] Finished at: 2020-09-11T00:26:03+02:00
 [INFO] ------------------------------------------------------------------------
```

**Comment by jhpoelen** [comment]
Same behavior was observed on indexing iNaturalist on 2020-09-19T02:11:17+02:00  . Attempting to reproduce.

**Comment by jhpoelen** [comment]
Looks to be an intermittent failure that does not occur at the same location / time: in attempting to reproduce the index failure, the error did not occur.

**Comment by jhpoelen** [comment]
Root cause was a OS-level configuration in which a temporary ram disk for indexing was prematurely removed. I was able to reproduce the issue by manually removing the ramdisk. Issue has been resolved by ensuring that ramdisk is not prematurely removed as part of a periodic update check.
