### ISSUE TITLE
NOAA REEM data access points have changed causing unexpected errors

### ISSUE THREAD

**Issue by jhpoelen** [globalbioticinteractions/globalbioticinteractions#687]
Previously, ```http://access.afsc.noaa.gov/REEM/WebDietData/showdata5.php?NODC=1&Region=AI``` returned formatted data, but as recent as 2021-08-07T03:30:53.350Z, the following response is recorded:

```html
<html>

<head>
<meta HTTP-EQUIV="Content-Type" Content="text/html; charset=Windows-1252">


<title>AFSC Application Server</title>
</head>

<body bgcolor=white>

Welcome to the Alaska Fisheries Science Center application server.<br><br>
The following applications were migrated from the old access.afsc.noaa.gov site to this server in 2021.  Please make sure to update any bookmarks you may have previously used.<br>
If you are looking for an application that is not in this list, or would like more details, please visit the <a href="https://www.fisheries.noaa.gov/about/alaska-fisheries-science-center">NOAA Fisheries - Alaska Fisheries Science Center Site</a>.

<br>
<ul>
	<li><a href="https://apps-afsc.fisheries.noaa.gov/pubs/search.php">AFSC Yearly Publications Poster Database</a></li>
	<li><a href="https://apps-afsc.fisheries.noaa.gov/al/collection_details/collection_search.php">Aging Method Database</a></li>
	<li><a href="https://apps-afsc.fisheries.noaa.gov/al/requests/requests.php">Aging Request Status</a></li>
	<li><a href="https://apps-afsc.fisheries.noaa.gov/furseal/search.php#top">Alaska Fur Seal Bibliography Database</a></li>
	<li><a href="https://apps-afsc.fisheries.noaa.gov/RACE/groundfish/survey_data/default.htm">Alaska Groundfish Survey 1982-2017 For Web</a></li>
	<li><a href="https://apps-afsc.fisheries.noaa.gov/REFM/Stocks/SARA/sara_access.php">Alaska Species Stock Assessment Results Archive</a></li>
	<li><a href="https://apps-afsc.fisheries.noaa.gov/sonarHabMap/search.php">Applicability of Sonars for Habitat Mapping Bibliography Database Search</a></li>
	<li><a href="https://apps-afsc.fisheries.noaa.gov/maps/fma/datamap/obsmap.html">Data Collected by Groundfish Observers</a></li>
	<li><a href="https://apps-afsc.fisheries.noaa.gov/icc/index.php">EcoFOCI Cruise Database </a></li>
	<li><a href="https://apps-afsc.fisheries.noaa.gov/REFM/Socioeconomics/Projects/communities/profiles.php">Fishing Communities of Alaska</a></li>
	<li><a href="https://apps-afsc.fisheries.noaa.gov/ichthyo/index.php">Ichthyoplankton Information System (IIS)</a></li>
	<li><a href="https://noaa-fisheries-afsc.data.socrata.com/w/u8e2-aznk/?cur=eWgoXHUIXFj&from=root">Interactive Research Locations Map</a></li>
	<li><a href="https://apps-afsc.fisheries.noaa.gov/mfge/search.php">Mobile Fishing Gear Effects Bibliography Database</a></li>
	<li><a href="https://apps-afsc.fisheries.noaa.gov/REFM/stocks/Historic_Assess.htm">North Pacific Groundfish Stock Assessment Archives</a></li>
	<li><a href="https://apps-afsc.fisheries.noaa.gov/furseal/rookeryimages/index.php">Northern Fur Seal Photo Archive</a></li>
	<li><a href="https://apps-afsc.fisheries.noaa.gov/al/otolith_inventory/searchform.php">Otolith Collection Inventory</a></li>
	<li><a href="https://apps-afsc.fisheries.noaa.gov/Publications/ProcRpts_intro.htm">Processed Reports</a></li>
	<li><a href="https://apps-afsc.fisheries.noaa.gov/pubs/search.php">Publications Database Search</a></li>
	<li><a href="https://apps-afsc.fisheries.noaa.gov/refm/reem/ecoweb/index.php">Resource Ecology and Ecosystem Modeling - Ecosystem Status Reports</a></li>
	<li><a href="https://apps-afsc.fisheries.noaa.gov/refm/reem/webdietdata/diettableintro.php">Resource Ecology and Ecosystem Modeling - Groundfish Diet Composition Tables</a></li>
	<li><a href="https://apps-afsc.fisheries.noaa.gov/refm/reem/webdietdata/dietdataintro.php">Resource Ecology and Ecosystem Modeling - Groundfish Diet Data</a></li>
	<li><a href="https://apps-afsc.fisheries.noaa.gov/refm/reem/lhweb/index.php">Resource Ecology and Ecosystem Modeling - Life History Database</a></li>
	<li><a href="https://apps-afsc.fisheries.noaa.gov/refm/reem/set/index.php">Resource Ecology and Ecosystem Modeling - Stomach Examiner's Tool</a></li>
	<li><a href="https://apps-afsc.fisheries.noaa.gov/Publications/techmemos.htm">Tech Memos</a></li>
</ul>


</body>
</html>
```

Incidentally, this caused some unexpected parsing issues.

**Comment by jhpoelen** [comment]
to reproduce:

```
$ elton review globalbioticinteractions/noaa-reem
...
ava.lang.ArrayIndexOutOfBoundsException: 0
	at org.eol.globi.data.DatasetImporterForMetaTable.parseValue(DatasetImporterForMetaTable.java:343)
	at org.eol.globi.data.DatasetImporterForMetaTable.parseColumnValue(DatasetImporterForMetaTable.java:286)
	at org.eol.globi.data.DatasetImporterForMetaTable.importAll(DatasetImporterForMetaTable.java:264)
	at org.eol.globi.data.DatasetImporterForMetaTable.importTable(DatasetImporterForMetaTable.java:129)
	at org.eol.globi.data.DatasetImporterForMetaTable.importStudy(DatasetImporterForMetaTable.java:67)
	at org.eol.globi.util.DatasetImportUtil.importDataset(DatasetImportUtil.java:65)
	at org.globalbioticinteractions.elton.cmd.CmdReview.review(CmdReview.java:154)
	at org.globalbioticinteractions.elton.cmd.CmdReview.reviewCachedOrRemote(CmdReview.java:116)
	at org.globalbioticinteractions.elton.cmd.CmdReview.run(CmdReview.java:107)
	at org.globalbioticinteractions.elton.cmd.CmdLine.run(CmdLine.java:15)
	at org.globalbioticinteractions.elton.cmd.CmdLine.run(CmdLine.java:24)
	at org.globalbioticinteractions.elton.Elton.main(Elton.java:15)
```

**Comment by jhpoelen** [comment]
Two actions were take:

1. An updated index configuration of NOAA REEM was released to Jorrit Poelen. (2021). globalbioticinteractions/noaa-reem: (v0.2). Zenodo. https://doi.org/10.5281/zenodo.5181449 . Note that the configuration was updated earlier, but not officially released, causing continued use of the previous configuration
2. Error handling was introduced via  https://github.com/globalbioticinteractions/globalbioticinteractions/commit/ad7781e6fc8b9d0fdd09a9019c37799af1127074 in an attempt to avoid this unexpected error to disrupt dataset indexing in the future.
