### ISSUE TITLE
Help Wanted: using Elton4N to generate neo4j database

### ISSUE THREAD

**Issue by zedomel** [globalbioticinteractions/globalbioticinteractions#846]
Hi @jhpoelen 

As you know, I'm using `Elton4N` to generate a neo4j database with data from GBIF DwC-A. But the taxon names are not getting processed/linked to the interactions source and target nodes. 
Here the command I'm using:

```bash
 java -cp elton4n-app.jar org.globalbioticinteractions.elton.Elton4N --taxonCache cache/taxonCache.tsv.gz -taxonMap cache/taxonMap.tsv.gz -neo4jVersion 3 -graphDbDir db/ -datasetDir cache/datasets/ -exportDir export
```

The output:
```
[main] INFO org.globalbioticinteractions.elton.Elton4N - Elton4N [version: 0.24.4-SNAPSHOT]
[main] INFO org.globalbioticinteractions.elton.Elton4N - processing steps: [link-names, link]
[main] INFO org.eol.globi.db.GraphServiceFactoryImpl - neo4j starting at [/media/external/projects/globi-gbif/db]...
[main] INFO org.eol.globi.db.GraphServiceFactoryImpl - done
[main] INFO org.eol.globi.tool.IndexerTaxa - resolving names with taxon cache ...
[main] INFO org.eol.globi.tool.NameResolver - name resolving started...
[main] INFO org.eol.globi.tool.NameResolver - resolving names...
[main] INFO org.eol.globi.util.NodeProcessorImpl - collecting [studies] node ids...
[main] INFO org.eol.globi.util.NodeProcessorImpl - collected 0 [studies] nodes in 0s (@ 0 nodes/ms)
[main] INFO org.eol.globi.util.NodeProcessorImpl - processing 0 [studies] nodes...
[main] INFO org.eol.globi.util.NodeProcessorImpl - processed 0 [studies] nodes in 0s (@ 0 nodes/ms)
[main] INFO org.eol.globi.tool.NameResolver - resolved [0] names in [0.00] taxon/s over [0.34] s
[main] INFO org.eol.globi.tool.NameResolver - name resolving complete.
[main] INFO org.eol.globi.tool.IndexerTaxa - adding same and similar terms for resolved taxa...
[main] INFO org.eol.globi.tool.IndexerTaxa - adding same and similar terms for resolved taxa done.
[main] INFO org.eol.globi.tool.IndexerTaxa - resolving names with taxon cache done.
[main] INFO org.eol.globi.tool.NameResolver - name resolving started...
[main] INFO org.eol.globi.tool.NameResolver - resolving names...
[main] INFO org.eol.globi.util.NodeProcessorImpl - collecting [studies] node ids...
[main] INFO org.eol.globi.util.NodeProcessorImpl - collected 0 [studies] nodes in 0s (@ 0 nodes/ms)
[main] INFO org.eol.globi.util.NodeProcessorImpl - processing 0 [studies] nodes...
[main] INFO org.eol.globi.util.NodeProcessorImpl - processed 0 [studies] nodes in 0s (@ 0 nodes/ms)
[main] INFO org.eol.globi.tool.NameResolver - resolved [0] names in [0.00] taxon/s over [0.01] s
[main] INFO org.eol.globi.tool.NameResolver - name resolving complete.
[main] INFO org.eol.globi.tool.TaxonInteractionIndexer - indexing interactions started...
[main] INFO org.eol.globi.util.NodeProcessorImpl - collecting [taxons] node ids...
[main] INFO org.eol.globi.util.NodeProcessorImpl - collected 0 [taxons] nodes in 0s (@ 0 nodes/ms)
[main] INFO org.eol.globi.util.NodeProcessorImpl - processing 0 [taxons] nodes...
[main] INFO org.eol.globi.util.NodeProcessorImpl - processed 0 [taxons] nodes in 0s (@ 0 nodes/ms)
[main] INFO org.eol.globi.tool.TaxonInteractionIndexer - created [0] taxon interactions in [NaN] taxon/s over [0.00] s
[main] INFO org.eol.globi.tool.TaxonInteractionIndexer - indexing interactions complete.
[main] INFO org.eol.globi.tool.IndexerTimed - LinkerTaxonIndex started...
[main] INFO org.eol.globi.util.NodeProcessorImpl - collecting [taxons] node ids...
[main] INFO org.eol.globi.util.NodeProcessorImpl - collected 0 [taxons] nodes in 0s (@ 0 nodes/ms)
[main] INFO org.eol.globi.util.NodeProcessorImpl - processing 0 [taxons] nodes...
[main] INFO org.eol.globi.util.NodeProcessorImpl - processed 0 [taxons] nodes in 0s (@ 0 nodes/ms)
[main] INFO org.eol.globi.tool.IndexerTimed - LinkerTaxonIndex completed in [0]s
[main] INFO org.eol.globi.tool.CmdGenerateReport - report for collection generating ...
[main] INFO org.eol.globi.util.NodeProcessorImpl - collecting [studies] node ids...
[main] INFO org.eol.globi.util.NodeProcessorImpl - collected 0 [studies] nodes in 0s (@ 0 nodes/ms)
[main] INFO org.eol.globi.util.NodeProcessorImpl - processing 0 [studies] nodes...
[main] INFO org.eol.globi.util.NodeProcessorImpl - processed 0 [studies] nodes in 0s (@ 0 nodes/ms)
[main] INFO org.eol.globi.tool.CmdGenerateReport - report for collection done.
[main] INFO org.eol.globi.tool.CmdGenerateReport - report for sources generating ...
[main] INFO org.eol.globi.util.NodeProcessorImpl - collecting [datasets] node ids...
[main] INFO org.eol.globi.util.NodeProcessorImpl - collected 0 [datasets] nodes in 0s (@ 0 nodes/ms)
[main] INFO org.eol.globi.util.NodeProcessorImpl - processing 0 [datasets] nodes...
[main] INFO org.eol.globi.util.NodeProcessorImpl - processed 0 [datasets] nodes in 0s (@ 0 nodes/ms)
[main] INFO org.eol.globi.tool.CmdGenerateReport - report for sources done.
[main] INFO org.eol.globi.tool.CmdGenerateReport - report for source organizations generating ...
[main] INFO org.eol.globi.util.NodeProcessorImpl - collecting [datasets] node ids...
[main] INFO org.eol.globi.util.NodeProcessorImpl - collected 0 [datasets] nodes in 0s (@ 0 nodes/ms)
[main] INFO org.eol.globi.util.NodeProcessorImpl - processing 0 [datasets] nodes...
[main] INFO org.eol.globi.util.NodeProcessorImpl - processed 0 [datasets] nodes in 0s (@ 0 nodes/ms)
[main] INFO org.eol.globi.tool.CmdGenerateReport - report for source organizations done.
[Thread-3] INFO org.eol.globi.db.GraphServiceFactoryImpl - neo4j stopping...
[Thread-3] INFO org.eol.globi.db.GraphServiceFactoryImpl - done.
```

I put the files that I'm using the in Zenodo: [https://doi.org/10.5281/zenodo.7357391](https://doi.org/10.5281/zenodo.7357391)

Any idea of what am I doing wrong?  The graph database has the interactions but there aren't any `Taxon` node. :-(

thanks.

**Comment by jhpoelen** [comment]
@zedomel thanks for sharing your detailed question / request for help.

Apologies for the awkward elton4n syntax - I think a little maintenance would work wonders to make the tool a little more usable.

But before I do that, please note the following:

elton4n has a couple of "steps" similar to mvn has phases. 

compile - imports dataset into graph db https://github.com/globalbioticinteractions/globalbioticinteractions/blob/262b7065f1a1889043707947d51b2559c2bcc96a/eol-globi-datasets/pom.xml#L117

link - links imported nodes using taxonCache/Map, generates indexes, and reports
https://github.com/globalbioticinteractions/globalbioticinteractions/blob/262b7065f1a1889043707947d51b2559c2bcc96a/eol-globi-datasets/pom.xml#L172

package - 
https://github.com/globalbioticinteractions/globalbioticinteractions/blob/262b7065f1a1889043707947d51b2559c2bcc96a/eol-globi-datasets/pom.xml#L265


to run all the phases / steps using elton4n would look something like 

 java org.globalbioticinteractions.elton.Elton4N --taxonCache cache/taxonCache.tsv.gz -taxonMap file://some/path/cache/taxonMap.tsv.gz -neo4jVersion 2 -graphDbDir db/ -datasetDir cache/datasets/ -exportDir compile link package

Note that neo4jVersion 2 should be used. The neo4jVersion3 using labels and implicit indexes (not legacy indexes) is not yet fully supported. Also, note that you have to include the jars unpackaged, otherwise neo4j appears to get confused about loading stuff.

On the globi server, the following script is used to rebuild a neo4j index and export data products from some elton dataset folder:

https://github.com/jhpoelen/globi-server-scripts/blob/main/build-index.sh

I suggest you use that script for your efforts also. 

However, I am open to suggestion on how to make elton4n a little easier to use.

Again, apologies for the convoluted how-to on Elton4N , the tool has mainly been used internally, and perhaps this is a good reason to make the tool easier to use. Your help / insights are much appreciated.

**Comment by zedomel** [comment]
Thank you @jhpoelen  for detailed explanation.

I was able to use `Elton4N` passing the steps like you said. But I'm getting the follow exception now:

```bash
java -cp elton4n-app.jar org.globalbioticinteractions.elton.Elton4N -datasetDir cache/datasets-test/ -exportDir ./export/ -graphDbDir ./db/ -neo4jVersion 2 -taxonCache /media/external/projects/globi-gbif/cache/taxonCache.tsv.gz -taxonMap /media/external/projects/globi-gbif/cache/taxonMap.tsv.gz compile link-names link package
```

```
[main] INFO org.globalbioticinteractions.elton.Elton4N - Elton4N [version: 0.24.4-SNAPSHOT]
[main] INFO org.globalbioticinteractions.elton.Elton4N - processing steps: [compile, link-names, link, package]
[main] INFO org.eol.globi.db.GraphServiceFactoryImpl - neo4j starting at [/media/external/projects/globi-gbif/./db]...
[main] INFO org.eol.globi.db.GraphServiceFactoryImpl - done
[main] INFO org.eol.globi.tool.IndexerDataset - found dataset namespaces: {002d7f3e3148965d09d33f552b42ec5f050c783e2cc4577b415f8cd0fc5bf198 | 10ff53e2ceca53a823b98239102a42416611b9bf5eb3d1ac4c4f79d601a6bb83}
[main] INFO org.eol.globi.data.DatasetImporterForRegistry - [002d7f3e3148965d09d33f552b42ec5f050c783e2cc4577b415f8cd0fc5bf198] checking status...
[main] INFO org.eol.globi.data.DatasetImporterForRegistry - [002d7f3e3148965d09d33f552b42ec5f050c783e2cc4577b415f8cd0fc5bf198] is active, importing...
[main] INFO org.gbif.dwc.terms.TermFactory - Property terms dcterms:contributor and dc:contributor are both known as "contributor". Keeping only earlier dcterms:contributor
[main] INFO org.gbif.dwc.terms.TermFactory - Property terms dcterms:coverage and dc:coverage are both known as "coverage". Keeping only earlier dcterms:coverage
[main] INFO org.gbif.dwc.terms.TermFactory - Property terms dcterms:creator and dc:creator are both known as "creator". Keeping only earlier dcterms:creator
[main] INFO org.gbif.dwc.terms.TermFactory - Property terms dcterms:date and dc:date are both known as "date". Keeping only earlier dcterms:date
[main] INFO org.gbif.dwc.terms.TermFactory - Property terms dcterms:description and dc:description are both known as "description". Keeping only earlier dcterms:description
[main] INFO org.gbif.dwc.terms.TermFactory - Property terms dcterms:format and dc:format are both known as "format". Keeping only earlier dcterms:format
[main] INFO org.gbif.dwc.terms.TermFactory - Property terms dcterms:identifier and dc:identifier are both known as "identifier". Keeping only earlier dcterms:identifier
[main] INFO org.gbif.dwc.terms.TermFactory - Property terms dcterms:language and dc:language are both known as "language". Keeping only earlier dcterms:language
[main] INFO org.gbif.dwc.terms.TermFactory - Property terms dcterms:publisher and dc:publisher are both known as "publisher". Keeping only earlier dcterms:publisher
[main] INFO org.gbif.dwc.terms.TermFactory - Property terms dcterms:relation and dc:relation are both known as "relation". Keeping only earlier dcterms:relation
[main] INFO org.gbif.dwc.terms.TermFactory - Property terms dcterms:rights and dc:rights are both known as "rights". Keeping only earlier dcterms:rights
[main] INFO org.gbif.dwc.terms.TermFactory - Property terms dcterms:source and dc:source are both known as "source". Keeping only earlier dcterms:source
[main] INFO org.gbif.dwc.terms.TermFactory - Property terms dcterms:subject and dc:subject are both known as "subject". Keeping only earlier dcterms:subject
[main] INFO org.gbif.dwc.terms.TermFactory - Property terms dcterms:title and dc:title are both known as "title". Keeping only earlier dcterms:title
[main] INFO org.gbif.dwc.terms.TermFactory - Property terms dcterms:type and dc:type are both known as "type". Keeping only earlier dcterms:type
[main] INFO org.gbif.dwc.terms.TermFactory - Property terms dcterms:identifier and acef:ID are both known as "ID". Keeping only earlier dcterms:identifier
[main] INFO org.gbif.dwc.terms.TermFactory - Class terms gbif:Distribution and acef:Distribution are both known as "Distribution". Keeping only earlier gbif:Distribution
[main] INFO org.gbif.dwc.terms.TermFactory - Class terms gbif:Reference and acef:Reference are both known as "Reference". Keeping only earlier gbif:Reference
[main] INFO org.gbif.dwc.terms.TermFactory - Class terms gbif:Reference and acef:Reference are both known as "References". Keeping only earlier gbif:Reference


[main] INFO org.eol.globi.data.DatasetImporterForRegistry - [002d7f3e3148965d09d33f552b42ec5f050c783e2cc4577b415f8cd0fc5bf198] imported in 35s
[main] INFO org.eol.globi.data.DatasetImporterForRegistry - [10ff53e2ceca53a823b98239102a42416611b9bf5eb3d1ac4c4f79d601a6bb83] checking status...
[main] INFO org.eol.globi.data.DatasetImporterForRegistry - [10ff53e2ceca53a823b98239102a42416611b9bf5eb3d1ac4c4f79d601a6bb83] is active, importing...
[main] INFO org.eol.globi.data.DatasetImporterForRegistry - [10ff53e2ceca53a823b98239102a42416611b9bf5eb3d1ac4c4f79d601a6bb83] imported in 0s
[main] INFO org.eol.globi.tool.IndexerTaxa - resolving names with taxon cache ...
[main] INFO org.eol.globi.tool.NameResolver - name resolving started...
[main] INFO org.eol.globi.tool.NameResolver - resolving names...
[main] INFO org.eol.globi.util.NodeProcessorImpl - collecting [studies] node ids...
[main] INFO org.eol.globi.util.NodeProcessorImpl - collected 4856 [studies] nodes in 0s (@ 30 nodes/ms)
[main] INFO org.eol.globi.util.NodeProcessorImpl - processing 4856 [studies] nodes...
[main] INFO org.eol.globi.taxon.TaxonCacheService - local taxon cache of [/media/external/projects/globi-gbif/cache/taxonCache.tsv.gz] building...
[main] ERROR org.globalbioticinteractions.elton.Elton4N - failed to run GloBI indexer with [-datasetDir cache/datasets-test/ -exportDir ./export/ -graphDbDir ./db/ -neo4jVersion 2 -taxonCache /media/external/projects/globi-gbif/cache/taxonCache.tsv.gz -taxonMap /media/external/projects/globi-gbif/cache/taxonMap.tsv.gz compile link-names link package]
java.lang.IllegalStateException: failed to instantiate taxonCache: [failed to open resource [/media/external/projects/globi-gbif/cache/taxonCache.tsv.gz]]
	at org.eol.globi.taxon.TaxonCacheService.initTaxonCache(TaxonCacheService.java:224)
	at org.eol.globi.taxon.TaxonCacheService.init(TaxonCacheService.java:145)
	at org.eol.globi.taxon.TaxonCacheService.lazyInit(TaxonCacheService.java:139)
	at org.eol.globi.taxon.TaxonCacheService.enrichAllMatches(TaxonCacheService.java:79)
	at org.eol.globi.taxon.ResolvingTaxonIndexNoTx.resolveAndIndex(ResolvingTaxonIndexNoTx.java:48)
	at org.eol.globi.taxon.ResolvingTaxonIndexNoTx.createTaxon(ResolvingTaxonIndexNoTx.java:40)
	at org.eol.globi.taxon.ResolvingTaxonIndexNoTx.getOrCreateTaxon(ResolvingTaxonIndexNoTx.java:35)
	at org.eol.globi.taxon.ResolvingTaxonIndexNoTx.getOrCreateTaxon(ResolvingTaxonIndexNoTx.java:19)
	at org.eol.globi.tool.NameResolver.resolveNamesInStudy(NameResolver.java:99)
	at org.eol.globi.tool.NameResolver.lambda$resolveNames$0(NameResolver.java:58)
	at org.eol.globi.util.NodeProcessorImpl.process(NodeProcessorImpl.java:82)
	at org.eol.globi.util.NodeUtil.processNodes(NodeUtil.java:194)
	at org.eol.globi.tool.NameResolver.resolveNames(NameResolver.java:66)
	at org.eol.globi.tool.NameResolver.index(NameResolver.java:133)
	at org.eol.globi.tool.IndexerTaxa.index(IndexerTaxa.java:45)
	at org.eol.globi.tool.CmdInterpretTaxa.run(CmdInterpretTaxa.java:34)
	at org.globalbioticinteractions.elton.Elton4N.importWithVersion(Elton4N.java:168)
	at org.globalbioticinteractions.elton.Elton4N.run(Elton4N.java:91)
	at org.globalbioticinteractions.elton.Elton4N.main(Elton4N.java:57)
Caused by: java.io.IOException: failed to open resource [/media/external/projects/globi-gbif/cache/taxonCache.tsv.gz]
	at org.eol.globi.util.ResourceServiceDataDir.retrieve(ResourceServiceDataDir.java:19)
	at org.eol.globi.util.ResourceServiceClasspathResource.retrieve(ResourceServiceClasspathResource.java:32)
	at org.eol.globi.util.ResourceServiceGzipAware.retrieve(ResourceServiceGzipAware.java:20)
	at org.eol.globi.util.ResourceServiceLocal.retrieve(ResourceServiceLocal.java:33)
	at org.eol.globi.service.CacheServiceUtil.createBufferedReader(CacheServiceUtil.java:15)
	at org.eol.globi.taxon.TaxonCacheService$3.<init>(TaxonCacheService.java:300)
	at org.eol.globi.taxon.TaxonCacheService.taxonCacheIterator(TaxonCacheService.java:299)
	at org.eol.globi.taxon.TaxonCacheService.initTaxonCache(TaxonCacheService.java:219)
	... 18 more
Exception in thread "main" java.lang.IllegalStateException: failed to instantiate taxonCache: [failed to open resource [/media/external/projects/globi-gbif/cache/taxonCache.tsv.gz]]
	at org.eol.globi.taxon.TaxonCacheService.initTaxonCache(TaxonCacheService.java:224)
	at org.eol.globi.taxon.TaxonCacheService.init(TaxonCacheService.java:145)
	at org.eol.globi.taxon.TaxonCacheService.lazyInit(TaxonCacheService.java:139)
	at org.eol.globi.taxon.TaxonCacheService.enrichAllMatches(TaxonCacheService.java:79)
	at org.eol.globi.taxon.ResolvingTaxonIndexNoTx.resolveAndIndex(ResolvingTaxonIndexNoTx.java:48)
	at org.eol.globi.taxon.ResolvingTaxonIndexNoTx.createTaxon(ResolvingTaxonIndexNoTx.java:40)
	at org.eol.globi.taxon.ResolvingTaxonIndexNoTx.getOrCreateTaxon(ResolvingTaxonIndexNoTx.java:35)
	at org.eol.globi.taxon.ResolvingTaxonIndexNoTx.getOrCreateTaxon(ResolvingTaxonIndexNoTx.java:19)
	at org.eol.globi.tool.NameResolver.resolveNamesInStudy(NameResolver.java:99)
	at org.eol.globi.tool.NameResolver.lambda$resolveNames$0(NameResolver.java:58)
	at org.eol.globi.util.NodeProcessorImpl.process(NodeProcessorImpl.java:82)
	at org.eol.globi.util.NodeUtil.processNodes(NodeUtil.java:194)
	at org.eol.globi.tool.NameResolver.resolveNames(NameResolver.java:66)
	at org.eol.globi.tool.NameResolver.index(NameResolver.java:133)
	at org.eol.globi.tool.IndexerTaxa.index(IndexerTaxa.java:45)
	at org.eol.globi.tool.CmdInterpretTaxa.run(CmdInterpretTaxa.java:34)
	at org.globalbioticinteractions.elton.Elton4N.importWithVersion(Elton4N.java:168)
	at org.globalbioticinteractions.elton.Elton4N.run(Elton4N.java:91)
	at org.globalbioticinteractions.elton.Elton4N.main(Elton4N.java:57)
Caused by: java.io.IOException: failed to open resource [/media/external/projects/globi-gbif/cache/taxonCache.tsv.gz]
	at org.eol.globi.util.ResourceServiceDataDir.retrieve(ResourceServiceDataDir.java:19)
	at org.eol.globi.util.ResourceServiceClasspathResource.retrieve(ResourceServiceClasspathResource.java:32)
	at org.eol.globi.util.ResourceServiceGzipAware.retrieve(ResourceServiceGzipAware.java:20)
	at org.eol.globi.util.ResourceServiceLocal.retrieve(ResourceServiceLocal.java:33)
	at org.eol.globi.service.CacheServiceUtil.createBufferedReader(CacheServiceUtil.java:15)
	at org.eol.globi.taxon.TaxonCacheService$3.<init>(TaxonCacheService.java:300)
	at org.eol.globi.taxon.TaxonCacheService.taxonCacheIterator(TaxonCacheService.java:299)
	at org.eol.globi.taxon.TaxonCacheService.initTaxonCache(TaxonCacheService.java:219)
	... 18 more
[Thread-3] INFO org.eol.globi.db.GraphServiceFactoryImpl - neo4j stopping...
[Thread-3] INFO org.eol.globi.db.GraphServiceFactoryImpl - done.
```

It is not locating the `taxonCache.tsv.gz` file, but it exists:

```bash
ls -lh /media/external/projects/globi-gbif/cache/taxonCache.tsv.gz
-rw-rw-r-- 1 jose jose 97M Nov 23 23:34 /media/external/projects/globi-gbif/cache/taxonCache.tsv.gz
```

```bash
cat /media/external/projects/globi-gbif/cache/taxonCache.tsv.gz | gunzip | head
id	name	rank	commonNames	path	pathIds	pathNames	externalUrl	thumbnailUrl
ALATaxon:007f413b-6738-4d5e-bee4-acf5229f0233	Hypholoma dispersum	species		Fungi | Basidiomycota | Agaricomycetes | Agaricomycetidae | Agaricales | Strophariaceae | Hypholoma | Hypholoma dispersum	ALATaxon:urn:lsid:indexfungorum.org:names:90156 | ALATaxon:urn:lsid:indexfungorum.org:names:90050 | ALATaxon:urn:lsid:indexfungorum.org:names:501297 | ALATaxon:urn:lsid:indexfungorum.org:names:501298 | ALATaxon:urn:lsid:indexfungorum.org:names:90508 | ALATaxon:urn:lsid:indexfungorum.org:names:81444 | ALATaxon:urn:lsid:indexfungorum.org:names:17828 | ALATaxon:007f413b-6738-4d5e-bee4-acf5229f0233	kingdom | phylum | class | subclass | order | family | genus | species	https://bie.ala.org.au/species/007f413b-6738-4d5e-bee4-acf5229f0233	
ALATaxon:008ab35e8347d95be1775b3ad5d710b8	Peronospora potentillae-anserinae	species		Chromista | Oomycota | Peronosporea | Peronosporales | Peronosporaceae | Peronospora | Peronospora potentillae-anserinae	ALATaxon:3520fbd4604c0d9890e037678776bfd2 | ALATaxon:15f4032e6086cbaf85add7bb0f7f2dd0 | ALATaxon:e6225b0521974a375a5c21c8c746356c | ALATaxon:4f0847779cccd256b28abcefd49a4514 | ALATaxon:81989755cc53a5f8edc0fbd8f095392b | ALATaxon:400298444f8965835d1a8d711e4cb6e2 | ALATaxon:008ab35e8347d95be1775b3ad5d710b8	kingdom | phylum | class | order | family | genus | species	https://bie.ala.org.au/species/008ab35e8347d95be1775b3ad5d710b8	
ALATaxon:00910d03-0485-4190-9686-06d7bce8f149	Agrocybe parasitica	species		Fungi | Basidiomycota | Agaricomycetes | Agaricomycetidae | Agaricales | Strophariaceae | Agrocybe | Agrocybe parasitica	ALATaxon:urn:lsid:indexfungorum.org:names:90156 | ALATaxon:urn:lsid:indexfungorum.org:names:90050 | ALATaxon:urn:lsid:indexfungorum.org:names:501297 | ALATaxon:urn:lsid:indexfungorum.org:names:501298 | ALATaxon:urn:lsid:indexfungorum.org:names:90508 | ALATaxon:urn:lsid:indexfungorum.org:names:81444 | ALATaxon:urn:lsid:indexfungorum.org:names:17034 | ALATaxon:00910d03-0485-4190-9686-06d7bce8f149	kingdom | phylum | class | subclass | order | family | genus | species	https://bie.ala.org.au/species/00910d03-0485-4190-9686-06d7bce8f149	
ALATaxon:0097e37d8cd587b90d2ced760726881a	Bordetella trematum	species		Bordetella trematum	ALATaxon:0097e37d8cd587b90d2ced760726881a	species	https://bie.ala.org.au/species/0097e37d8cd587b90d2ced760726881a	
ALATaxon:009afd00-6912-457c-b085-de22aa2aaf22	Puccinia purpurea	species		Fungi | Basidiomycota | Pucciniomycetes | Pucciniales | Pucciniaceae | Puccinia | Puccinia purpurea	ALATaxon:urn:lsid:indexfungorum.org:names:90156 | ALATaxon:urn:lsid:indexfungorum.org:names:90050 | ALATaxon:urn:lsid:indexfungorum.org:names:501494 | ALATaxon:urn:lsid:indexfungorum.org:names:501535 | ALATaxon:urn:lsid:indexfungorum.org:names:81311 | ALATaxon:urn:lsid:indexfungorum.org:names:16284 | ALATaxon:009afd00-6912-457c-b085-de22aa2aaf22	kingdom | phylum | class | order | family | genus | species	https://bie.ala.org.au/species/009afd00-6912-457c-b085-de22aa2aaf22	
ALATaxon:00c8158befee12409066b416412dc5f1	Didymium laxifilum	species		Protozoa | Mycetozoa | Myxomycetes | Physarales | Didymiaceae | Didymium | Didymium laxifilum	ALATaxon:NZOR-6-100174 | ALATaxon:45355e80b0240c3ec5d2cb22d299cecc | ALATaxon:71bdec4dc94fb1cd498ddbc973e93884 | ALATaxon:84c577558d91868849938a4dbbfabfd6 | ALATaxon:fbb912af2a56d0bf8003f89aeef0e06d | ALATaxon:00849e0c363d75f132cd8e2ab0335575 | ALATaxon:00c8158befee12409066b416412dc5f1	kingdom | phylum | class | order | family | genus | species	https://bie.ala.org.au/species/00c8158befee12409066b416412dc5f1	
ALATaxon:00c9a715235ab56251e78ee52844c7b9	Campylobacter volucris	species		Proteobacteria | Epsilonproteobacteria | Campylobacterales | Campylobacteraceae | Campylobacter | Campylobacter volucris	ALATaxon:NZOR-6-129863 | ALATaxon:NZOR-6-15072 | ALATaxon:NZOR-6-87804 | ALATaxon:NZOR-6-1403 | ALATaxon:NZOR-6-112234 | ALATaxon:00c9a715235ab56251e78ee52844c7b9	phylum | class | order | family | genus | species	https://bie.ala.org.au/species/00c9a715235ab56251e78ee52844c7b9	
ALATaxon:00d35f97f119cdbbc89102b7f8e1c49c	Licea punctiformis	species		Protozoa | Mycetozoa | Myxomycetes | Liceales | Liceaceae | Licea | Licea punctiformis	ALATaxon:NZOR-6-100174 | ALATaxon:45355e80b0240c3ec5d2cb22d299cecc | ALATaxon:71bdec4dc94fb1cd498ddbc973e93884 | ALATaxon:3a9b4b9e59e7f2216c4a84994cfe3d13 | ALATaxon:2434af413b05d9887666eaa44ed25ae3 | ALATaxon:a6f11f9a08a005b801b1e8491cdc9f6e | ALATaxon:00d35f97f119cdbbc89102b7f8e1c49c	kingdom | phylum | class | order | family | genus | species	https://bie.ala.org.au/species/00d35f97f119cdbbc89102b7f8e1c49c	
ALATaxon:00dbdd03-8748-4f8e-910c-998e59465048	Thecaphora lagenophorae	species		Fungi | Basidiomycota | Ustilaginomycetes | Urocystidales | Glomosporiaceae | Thecaphora | Thecaphora lagenophorae	ALATaxon:urn:lsid:indexfungorum.org:names:90156 | ALATaxon:urn:lsid:indexfungorum.org:names:90050 | ALATaxon:urn:lsid:indexfungorum.org:names:90393 | ALATaxon:urn:lsid:indexfungorum.org:names:506561 | ALATaxon:urn:lsid:indexfungorum.org:names:80806 | ALATaxon:urn:lsid:indexfungorum.org:names:16347 | ALATaxon:00dbdd03-8748-4f8e-910c-998e59465048	kingdom | phylum | class | order | family | genus | species	https://bie.ala.org.au/species/00dbdd03-8748-4f8e-910c-998e59465048
```

Any idea?

Thanks

**Comment by jhpoelen** [comment]
@zedomel thanks for sharing the details, and apologies for elton4n being so picky . . . 

you have to make sure to turn the path into the URI - 

so instead of:

```/media/external/projects/globi-gbif/cache/taxonCache.tsv.gz```

say

```file:///media/external/projects/globi-gbif/cache/taxonCache.tsv.gz```

**Comment by jhpoelen** [comment]
for a full example would be:

```
java -cp elton4n-app.jar org.globalbioticinteractions.elton.Elton4N -datasetDir cache/datasets-test/ -exportDir ./export/ -graphDbDir ./db/ -neo4jVersion 2 -taxonCache file:///media/external/projects/globi-gbif/cache/taxonCache.tsv.gz -taxonMap file:///media/external/projects/globi-gbif/cache/taxonMap.tsv.gz compile link-names link package
```
especially note the ```-neo4jVersion 2``` . Please do *not* use ```-neo4jVersion 3``` as this is not yet fully supported. 

@zedomel if you are concerned about performance, please share some timed examples - ideally one example with a relatively small DwC-A (e.g., UCSB-IZC) and another with a big one (like Smithsonian). Also, please share what you'd like to see as far as performance goes. 

Finally, please share the hash of the GBIF snapshot that you are using. . .

**Comment by jhpoelen** [comment]
via v0.25.2 elton4n.deb package, you can now do things like:

```
elton update globalbioticinteractions/template-dataset
elton4n compile
elton4n link
elton4n package
```

if you'd like to provide taxonCache/Map resources, please use:

```
elton4n link -taxonCache taxonCache.tsv.gz -taxonMap taxonMap.tsv.gz 
```
 
or similar, instead of using the default taxon mapping for elton4n : the identity mapping (i.e., no:match mapping)
