### ISSUE TITLE
Property value size is too large for index. Please see index documentation for limitations

### ISSUE THREAD

**Issue by zedomel** [globalbioticinteractions/globalbioticinteractions#857]
Hi @jhpoelen 

During the execution of  `elton4n` the follow exception occurred and VM stopped:
```java
[main] ERROR org.globalbioticinteractions.elton.Elton4N - failed to run GloBI indexer with [-datasetDir /home/externo/joseas/gbif-interactions/datasets/ -graphDbDir ./graph.db/ -taxonCache /dados1/jose/elton4n/cache/taxonCache.tsv.gz -taxonMap /dados1/jose/elton4n/cache/taxonMap.tsv.gz compile link link-names]
java.lang.IllegalArgumentException: Property value size is too large for index. Please see index documentation for limitations.
        at org.neo4j.kernel.impl.api.AbstractIndexKeyLengthValidator.validateLength(AbstractIndexKeyLengthValidator.java:59)
        at org.neo4j.kernel.impl.api.IndexTextValueLengthValidator.validate(IndexTextValueLengthValidator.java:47)
        at org.neo4j.kernel.impl.api.LuceneIndexValueValidator.validate(LuceneIndexValueValidator.java:60)
        at org.neo4j.kernel.impl.api.ExplicitIndexValueValidator.validate(ExplicitIndexValueValidator.java:45)
        at org.neo4j.index.impl.lucene.explicit.LuceneExplicitIndex.assertValidValue(LuceneExplicitIndex.java:145)
        at org.neo4j.index.impl.lucene.explicit.LuceneExplicitIndex.addNode(LuceneExplicitIndex.java:109)
        at org.neo4j.kernel.impl.newapi.Operations.nodeAddToExplicitIndex(Operations.java:712)
        at org.neo4j.kernel.impl.coreapi.ExplicitIndexProxy$1.add(ExplicitIndexProxy.java:96)
        at org.neo4j.kernel.impl.coreapi.ExplicitIndexProxy.internalAdd(ExplicitIndexProxy.java:481)
        at org.neo4j.kernel.impl.coreapi.ExplicitIndexProxy.add(ExplicitIndexProxy.java:342)
        at org.eol.globi.data.NodeFactoryNeo4j2.indexLocation(NodeFactoryNeo4j2.java:152)
        at org.eol.globi.data.NodeFactoryNeo4j.createLocation(NodeFactoryNeo4j.java:112)
        at org.eol.globi.data.NodeFactoryNeo4j.getOrCreateLocation(NodeFactoryNeo4j.java:353)
        at org.eol.globi.data.NodeFactoryNeo4j.getOrCreateLocation(NodeFactoryNeo4j.java:57)
        at org.eol.globi.data.NodeFactoryWithDatasetContext.getOrCreateLocation(NodeFactoryWithDatasetContext.java:90)
        at org.eol.globi.process.InteractionImporter.getOrCreateLocation(InteractionImporter.java:374)
        at org.eol.globi.process.InteractionImporter.importInteraction(InteractionImporter.java:165)
        at org.eol.globi.process.InteractionImporter.on(InteractionImporter.java:108)
        at org.eol.globi.process.InteractionListenerImpl.on(InteractionListenerImpl.java:77)
        at org.eol.globi.data.DatasetImporterForTSV.importResource(DatasetImporterForTSV.java:255)
        at org.eol.globi.data.DatasetImporterForTSV.importResource(DatasetImporterForTSV.java:217)
        at org.eol.globi.data.DatasetImporterForTSV.importRepository(DatasetImporterForTSV.java:195)
        at org.eol.globi.data.DatasetImporterForTSV.importStudy(DatasetImporterForTSV.java:186)
        at org.eol.globi.data.DatasetImporterForRegistry.importData(DatasetImporterForRegistry.java:89)
        at org.eol.globi.data.DatasetImporterForRegistry.importData(DatasetImporterForRegistry.java:63)
        at org.eol.globi.data.DatasetImporterForRegistry.importStudy(DatasetImporterForRegistry.java:43)
        at org.eol.globi.tool.IndexerDataset.indexDatasets(IndexerDataset.java:75)
        at org.eol.globi.tool.IndexerDataset.index(IndexerDataset.java:47)
        at org.eol.globi.tool.CmdImportDatasets.run(CmdImportDatasets.java:26)
        at org.globalbioticinteractions.elton.Elton4N.importWithVersion(Elton4N.java:168)
        at org.globalbioticinteractions.elton.Elton4N.run(Elton4N.java:91)
        at org.globalbioticinteractions.elton.Elton4N.main(Elton4N.java:57)
```

The latest entries in `logs/debug.log`:
```
2022-12-13 13:04:58.351+0000 INFO [o.n.k.NeoStoreDataSource] Rotated to transaction log [/home/externo/joseas/graph.db/neostore.transaction.db.48] version=48, last transaction in previous log=821
2022-12-13 13:05:41.696+0000 INFO [o.n.k.i.t.l.c.CheckPointerImpl] Checkpoint triggered by "Scheduled checkpoint for time threshold" @ txId: 830 checkpoint started...
2022-12-13 13:05:41.733+0000 INFO [o.n.k.i.s.c.CountsTracker] Rotated counts store at transaction 830 to [/home/externo/joseas/graph.db/neostore.counts.db.a], from [/home/externo/joseas/graph.db/neostore.counts.db.b].
2022-12-13 13:05:41.841+0000 INFO [o.n.k.i.t.l.c.CheckPointerImpl] Checkpoint triggered by "Scheduled checkpoint for time threshold" @ txId: 830 checkpoint completed in 145ms
2022-12-13 13:05:41.898+0000 INFO [o.n.k.i.t.l.p.LogPruningImpl] Pruned log versions 46-46, last checkpoint was made in version 48
2022-12-13 13:05:45.675+0000 WARN [o.n.k.i.c.VmPauseMonitorComponent] Detected VM stop-the-world pause: {pauseTime=112, gcTime=0, gcCount=0}
2022-12-13 13:06:13.735+0000 INFO [o.n.k.NeoStoreDataSource] Rotated to transaction log [/home/externo/joseas/graph.db/neostore.transaction.db.49] version=49, last transaction in previous log=838
2022-12-13 13:06:16.707+0000 WARN [o.n.k.i.c.VmPauseMonitorComponent] Detected VM stop-the-world pause: {pauseTime=148, gcTime=173, gcCount=1}
2022-12-13 13:06:28.277+0000 INFO [o.n.g.f.GraphDatabaseFacadeFactory] Shutdown started
2022-12-13 13:06:28.279+0000 INFO [o.n.k.a.DatabaseAvailabilityGuard] Database graph.db is unavailable.
2022-12-13 13:06:28.281+0000 INFO [o.n.g.f.GraphDatabaseFacadeFactory] Shutting down 'graph.db' database.
2022-12-13 13:06:28.281+0000 INFO [o.n.g.f.GraphDatabaseFacadeFactory] Shutdown started
2022-12-13 13:06:28.288+0000 INFO [o.n.k.i.t.l.c.CheckPointerImpl] Checkpoint triggered by "Database shutdown" @ txId: 840 checkpoint started...
2022-12-13 13:06:28.461+0000 INFO [o.n.k.i.s.c.CountsTracker] Rotated counts store at transaction 840 to [/home/externo/joseas/graph.db/neostore.counts.db.b], from [/home/externo/joseas/graph.db/neostore.counts.db.a].
2022-12-13 13:06:28.532+0000 INFO [o.n.k.i.t.l.c.CheckPointerImpl] Checkpoint triggered by "Database shutdown" @ txId: 840 checkpoint completed in 244ms
2022-12-13 13:06:28.583+0000 INFO [o.n.k.i.t.l.p.LogPruningImpl] Pruned log versions 47-47, last checkpoint was made in version 49
2022-12-13 13:06:28.653+0000 INFO [o.n.i.d.DiagnosticsManager] --- STOPPING diagnostics START ---
2022-12-13 13:06:28.653+0000 INFO [o.n.i.d.DiagnosticsManager] --- STOPPING diagnostics END ---
```

If needed I can share the `interactions.tsv`.

thanks.

**Comment by jhpoelen** [comment]
@zedomel issue was reproduced in a test case and the root cause was an unchecked exception that caused elton4n to stop prematurely. Currently, the exception is caught and should be handle gracefully without making elton4n stop prematurely. Also, warning messages should be logged when overly large texts are attempted to be indexed. 

Fix available in just released v0.25.0 . For release notes and deb package, see https://github.com/globalbioticinteractions/globalbioticinteractions/releases/tag/v0.25.0 .

Please confirm you were able to install and run elton4n v0.25.0 . 

Thanks for being patient, and please comment/ re-open issue if the issue has not been addressed.

**Comment by jhpoelen** [comment]
@zedomel please note that the elton4n commandline interface is slightly different:

instead of 

elton4n [options] command

you should now do:

elton4n command [options]

for instance, now, you can specify the export dir by:

elton4n package -exportDir ./target

Apologies for the possible confusion / rework here, I migrated elton4n to use the same framework at elton/nomer/preston, and this was a side effect.

**Comment by zedomel** [comment]
> @zedomel issue was reproduced in a test case and the root cause was an unchecked exception that caused elton4n to stop prematurely. Currently, the exception is caught and should be handle gracefully without making elton4n stop prematurely. Also, warning messages should be logged when overly large texts are attempted to be indexed in an explicit neo4j index.
> 
> Fix available in just released v0.25.0 . For release notes and deb package, see https://github.com/globalbioticinteractions/globalbioticinteractions/releases/tag/v0.25.0 .
> 
> Please confirm you were able to install and run elton4n v0.25.0 .
> 
> Thanks for being patient, and please comment/ re-open issue if the issue has not been addressed.

@jhpoelen thanks for fixing it so quickly. I installed elton4n v0.25.0 from deb package and now it is running.

I will maintain you informed about the progress on that.

Thank you.

**Comment by zedomel** [comment]
Hi @jhpoelen 

Do you have any idea how I can solve this problem **Property value size is too large for index**?
The execution of `etlton4` was stopped after the exception and I'm not sure if the dataset was compiled.

The `elton4n` output:
[elton-compile-time.log](https://github.com/globalbioticinteractions/globalbioticinteractions/files/10236357/elton-compile-time.log)

thanks

**Comment by jhpoelen** [comment]
@zedomel thanks for sharing the log and re-opening. Right now, a dataset stops importing whenever a single line is causing it to choke. Is it correct that you've put all interactions into a single dataset ?

**Comment by jhpoelen** [comment]
I am just trying to figure out how to best report on the issue - you'd want to know about it right? And, perhaps log a warning and continue. Please let me know what you'd like elton4n to do when encountering an issue processing/indexing an interaction.

**Comment by jhpoelen** [comment]
Another thing I could do it truncate the value and log a warning, saying that the value was truncated to fit the index.

**Comment by jhpoelen** [comment]
Or perhaps drop the location index all together . . . I am not aware of anyone using it anyway ; )

**Comment by jhpoelen** [comment]
@zedomel I just release https://github.com/globalbioticinteractions/globalbioticinteractions/releases/tag/v0.25.1 . I ended up simply not indexing values are too large for a neo4j index. The original values should still be retained in the neo4j graph. 

Apologies for the repeat issue, and please let me know if v0.25.1 keeps processing as expected.

**Comment by zedomel** [comment]
Thank you @jhpoelen. 
It is running.... I will keep you informed.

thanks
josé
