### ISSUE TITLE
"no checkpoint found" error in neo4j causes intermittent search index issues

### ISSUE THREAD

**Issue by jhpoelen** [globalbioticinteractions/globalbioticinteractions#913]
It appears that the read-only neo4j index that helps power the GloBI API has intermittent issues which prevents neo4j from restarting. 

workaround - re-install pre-computed neo4j index

```
-- Logs begin at Mon 2023-08-07 04:02:46 CEST, end at Mon 2023-08-07 14:40:40 CEST. --
Aug 07 06:58:25 repo.jhpoelen.nl systemd[1]: neo4j.service: Main process exited, code=killed, status=9/KILL
Aug 07 06:58:25 repo.jhpoelen.nl systemd[1]: neo4j.service: Failed with result 'signal'.
Aug 07 06:58:25 repo.jhpoelen.nl systemd[1]: neo4j.service: Scheduled restart job, restart counter is at 1.
Aug 07 06:58:25 repo.jhpoelen.nl systemd[1]: Stopped Neo4j Graph Database.
Aug 07 06:58:25 repo.jhpoelen.nl systemd[1]: Started Neo4j Graph Database.
Aug 07 06:58:25 repo.jhpoelen.nl neo4j[2218606]: Active database: graph.db
Aug 07 06:58:25 repo.jhpoelen.nl neo4j[2218667]: Directories in use:
Aug 07 06:58:25 repo.jhpoelen.nl neo4j[2218667]:   home:         /var/lib/neo4j
Aug 07 06:58:25 repo.jhpoelen.nl neo4j[2218667]:   config:       /etc/neo4j
Aug 07 06:58:25 repo.jhpoelen.nl neo4j[2218667]:   logs:         /var/log/neo4j
Aug 07 06:58:25 repo.jhpoelen.nl neo4j[2218667]:   plugins:      /var/lib/neo4j/plugins
Aug 07 06:58:25 repo.jhpoelen.nl neo4j[2218667]:   import:       /var/lib/neo4j/import
Aug 07 06:58:25 repo.jhpoelen.nl neo4j[2218667]:   data:         /var/lib/neo4j/data
Aug 07 06:58:25 repo.jhpoelen.nl neo4j[2218667]:   certificates: /var/lib/neo4j/certificates
Aug 07 06:58:25 repo.jhpoelen.nl neo4j[2218667]:   run:          /var/run/neo4j
Aug 07 06:58:25 repo.jhpoelen.nl neo4j[2218606]: Starting Neo4j.
Aug 07 06:58:27 repo.jhpoelen.nl neo4j[2218606]: 2023-08-07 04:58:27.010+0000 INFO  ======== Neo4j 3.5.35 ========
Aug 07 06:58:27 repo.jhpoelen.nl neo4j[2218606]: 2023-08-07 04:58:27.021+0000 INFO  Starting...
Aug 07 06:58:28 repo.jhpoelen.nl neo4j[2218606]: 2023-08-07 04:58:28.424+0000 ERROR Failed to start Neo4j: Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@65f00478' was successfully initialized, but failed to start. Please see the attached cause exception "No check point found in any log file from version 465 to 465". Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@65f00478' was successfully initialized, but failed to start. Please see the attached cause exception "No check point found in any log file from version 465 to 465".
Aug 07 06:58:28 repo.jhpoelen.nl neo4j[2218606]: org.neo4j.server.ServerStartupException: Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@65f00478' was successfully initialized, but failed to start. Please see the attached cause exception "No check point found in any log file from version 465 to 465".
Aug 07 06:58:28 repo.jhpoelen.nl neo4j[2218606]:         at org.neo4j.server.exception.ServerStartupErrors.translateToServerStartupError(ServerStartupErrors.java:45)
Aug 07 06:58:28 repo.jhpoelen.nl neo4j[2218606]:         at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:187)
Aug 07 06:58:28 repo.jhpoelen.nl neo4j[2218606]:         at org.neo4j.server.ServerBootstrapper.start(ServerBootstrapper.java:124)
Aug 07 06:58:28 repo.jhpoelen.nl neo4j[2218606]:         at org.neo4j.server.ServerBootstrapper.start(ServerBootstrapper.java:91)
Aug 07 06:58:28 repo.jhpoelen.nl neo4j[2218606]:         at org.neo4j.server.CommunityEntryPoint.main(CommunityEntryPoint.java:32)
Aug 07 06:58:28 repo.jhpoelen.nl neo4j[2218606]: Caused by: org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.server.database.LifecycleManagingDatabase@65f00478' was successfully initialized, but failed to start. Please see the attached cause exception "No check point found in any log file from version 465 to 465".
Aug 07 06:58:28 repo.jhpoelen.nl neo4j[2218606]:         at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:473)
Aug 07 06:58:28 repo.jhpoelen.nl neo4j[2218606]:         at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:111)
Aug 07 06:58:28 repo.jhpoelen.nl neo4j[2218606]:         at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:180)
```

**Comment by jhpoelen** [comment]
An automated workaround was implemented to reset the neo4j index whenever neo4j becomes unresponsive. 

Addressing the root cause is still ongoing. . .
