### ISSUE TITLE
DwC-A import for large resource causes indexing interruption due to "GC overhead limit exceeded"

### ISSUE THREAD

**Issue by jhpoelen** [globalbioticinteractions/globalbioticinteractions#949]
when indexing https://github.com/globalbioticinteractions/inaturalist with elton4n,

the following is observed 

```
 [main] INFO org.eol.globi.data.DatasetImporterForRSS - including [http://iNaturalist.org is a place where you can record what you see in nature, meet other nature lovers, and learn about t>
 [main] INFO org.eol.globi.data.DatasetImporterForRSS - including [iNaturalist Taxa].
 [main] INFO org.eol.globi.data.DatasetImporterForRSS - including [http://iNaturalist.org is a place where you can record what you see in nature, meet other nature lovers, and learn about t>
 [main] INFO org.eol.globi.data.DatasetImporterForRSS - including [iNaturalist Taxa].
 [main] INFO org.eol.globi.util.DatasetImportUtil - indexing unresolved occurrence references of [rss.xml]...
 [main] INFO org.eol.globi.util.DatasetImportUtil - indexing unresolved occurrence references of [rss.xml] done: indexed [30702] unresolved occurrences
 [main] INFO org.eol.globi.util.DatasetImportUtil - indexing dependencies of [rss.xml]...
 java.lang.OutOfMemoryError: GC overhead limit exceeded
         at java.util.regex.Matcher.<init>(Matcher.java:226)
         at java.util.regex.Pattern.matcher(Pattern.java:1093)
         at org.gbif.dwc.record.CleanUtils.clean(CleanUtils.java:35)
         at org.gbif.dwc.record.RecordImpl.column(RecordImpl.java:81)
         at org.gbif.dwc.record.RecordImpl.value(RecordImpl.java:118)
         at org.gbif.dwc.record.RecordImpl.value(RecordImpl.java:139)
         at org.eol.globi.data.DatasetImporterForDwCA.termsToMap(DatasetImporterForDwCA.java:1266)
         at org.eol.globi.data.DatasetImporterForDwCA.linkTerm(DatasetImporterForDwCA.java:1189)
         at org.eol.globi.data.DatasetImporterForDwCA.attemptLinkUsingTerm(DatasetImporterForDwCA.java:1177)
         at org.eol.globi.data.DatasetImporterForDwCA.resolveLocalResourceIds(DatasetImporterForDwCA.java:1127)
         at org.eol.globi.data.DatasetImporterForDwCA.importResourceRelationshipExtension(DatasetImporterForDwCA.java:957)
         at org.eol.globi.data.DatasetImporterForDwCA.importResourceRelationshipExtension(DatasetImporterForDwCA.java:923)
         at org.eol.globi.data.DatasetImporterForDwCA.importStudy(DatasetImporterForDwCA.java:274)
         at org.eol.globi.util.DatasetImportUtil.importDataset(DatasetImportUtil.java:66)
         at org.eol.globi.util.DatasetImportUtil.importDataset(DatasetImportUtil.java:39)
         at org.eol.globi.util.DatasetImportUtil.indexDatasets(DatasetImportUtil.java:149)
         at org.eol.globi.util.DatasetImportUtil.resolveDependencies(DatasetImportUtil.java:94)
         at org.eol.globi.util.DatasetImportUtil.resolveAndImportDatasets(DatasetImportUtil.java:79)
         at org.eol.globi.data.DatasetImporterForRSS.importStudy(DatasetImporterForRSS.java:46)
         at org.eol.globi.data.DatasetImporterForRegistry.importData(DatasetImporterForRegistry.java:89)
         at org.eol.globi.data.DatasetImporterForRegistry.importData(DatasetImporterForRegistry.java:63)
         at org.eol.globi.data.DatasetImporterForRegistry.importStudy(DatasetImporterForRegistry.java:43)
         at org.eol.globi.tool.IndexerDataset.indexDatasets(IndexerDataset.java:75)
         at org.eol.globi.tool.IndexerDataset.index(IndexerDataset.java:47)
         at org.eol.globi.tool.CmdCompile.run(CmdCompile.java:25)
         at picocli.CommandLine.executeUserObject(CommandLine.java:1939)
         at picocli.CommandLine.access$1300(CommandLine.java:145)
         at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
         at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
         at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
         at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
         at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
 [Thread-3] INFO org.eol.globi.db.GraphServiceFactoryImpl - neo4j stopping...
 [Thread-3] INFO org.eol.globi.db.GraphServiceFactoryImpl - done.
 [INFO] ------------------------------------------------------------------------
 [INFO] BUILD FAILURE
 [INFO] ------------------------------------------------------------------------
 [INFO] Total time:  49:47 min

```

**Comment by jhpoelen** [comment]
after various optimization via, 
 2677150b46a56ea9c5be845a7a1a54db401936a9
 3edced81ff5295a58506469f50d8e986cd892c6c
 92988dc9539d69e3c51993ac5993b2ee26e54c82
 3268b1958e15aadcbc365ef5d129714bc7a87d6a
 3b05a26b65d6493a141fa1dedea4d7060603f53d
 366fc847a5a3056cf8e42159b5acd7400a86777b
 a8575ea717b7da40a643b73f09258fdaaeb74c83

the "GC Overhead Limit Exceeded" behavior is no longer detected -

The root cause appears to have been the creation of new strings. 

For instance, every time the ```org.gbif.dwc.terms.Term:qualifiedName()``` is called, a new string is created. 

https://github.com/gbif/dwc-api/blob/a74c2790085ab1f0fcb2252ffd8d7217cde7fefa/src/main/java/org/gbif/dwc/terms/Term.java#L64

To prevent the creation of these millions and millions of strings, I created a term cache (similar to GBIF's TermFactory) that pre-computes the qualified name string. See https://github.com/globalbioticinteractions/globalbioticinteractions/blob/2677150b46a56ea9c5be845a7a1a54db401936a9/eol-globi-data-sources/src/main/java/org/eol/globi/data/DatasetImporterForDwCA.java#L1140 

I am sure this solution can be optimized further, but at least for now the pressure on the garbage collector (GC) is somewhat reduced.

```
 [main] INFO org.eol.globi.data.DatasetImporterForRegistry - [globalbioticinteractions/inaturalist] is active, importing...
 [main] INFO org.eol.globi.data.DatasetImporterForRSS - including [http://iNaturalist.org is a place where you can record what you see in nature, meet other nature lovers, and learn about t>
 [main] INFO org.eol.globi.data.DatasetImporterForRSS - including [iNaturalist Taxa].
 [main] INFO org.eol.globi.data.DatasetImporterForRSS - including [http://iNaturalist.org is a place where you can record what you see in nature, meet other nature lovers, and learn about t>
 [main] INFO org.eol.globi.data.DatasetImporterForRSS - including [iNaturalist Taxa].
 [main] INFO org.eol.globi.util.DatasetImportUtil - indexing unresolved occurrence references of [rss.xml]...
 [main] INFO org.eol.globi.util.DatasetImportUtil - indexing unresolved occurrence references of [rss.xml] done: indexed [30702] unresolved occurrences
 [main] INFO org.eol.globi.util.DatasetImportUtil - indexing dependencies of [rss.xml]...
 [main] INFO org.eol.globi.util.DatasetImportUtil - indexing dependencies of [rss.xml] done: resolved [30702] occurrence references
 [main] INFO org.eol.globi.util.DatasetImportUtil - importing datasets for [rss.xml]...
 [main] INFO org.eol.globi.util.DatasetImportUtil - importing datasets for [rss.xml] done.
 [main] INFO org.eol.globi.data.DatasetImporterForRegistry - [globalbioticinteractions/inaturalist] imported in 705s
```

**Comment by jhpoelen** [comment]
The changes also have appeared to speed up the indexing process. 

A largish DwC-A collection by USNM (~10M occurrences with >200k interaction claims) previously indexed in 1326s (22 min), now in 810s (or 13 min). 

```
Dec 06 23:47:24 [main] INFO org.eol.globi.data.DatasetImporterForRegistry - [globalbioticinteractions/usnm] imported in 1326s
Dec 07 00:33:45 [main] INFO org.eol.globi.data.DatasetImporterForRegistry - [globalbioticinteractions/usnm] imported in 810s
```
